# Generated by Django 4.0.2 on 2022-02-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produtor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtor',
            options={'verbose_name_plural': 'produtores'},
        ),
        migrations.AlterModelOptions(
            name='regiao',
            options={'verbose_name_plural': 'regioes'},
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.categoria')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.regiao')),
            ],
        ),
    ]
