# Generated by Django 4.0.2 on 2022-02-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produtor_options_alter_regiao_options_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produtores',
            field=models.ManyToManyField(related_name='produtos', to='core.Produtor'),
        ),
    ]
